import React from "react";
import { Link } from "react-router-dom";

export default function Dashboard() {
  return (
    <div className="min-h-screen bg-gray-100 p-8">
      <header className="flex justify-between items-center mb-8">
        <h1 className="text-3xl font-bold text-blue-600">Smart Study Buddy</h1>
        <nav className="space-x-4">
          <Link to="/" className="text-gray-700 hover:text-blue-600">
            Home
          </Link>
          <Link to="/workspaces" className="text-gray-700 hover:text-blue-600">
            My Workspaces
          </Link>
          <Link to="/stress-free" className="text-gray-700 hover:text-blue-600">
            Stress-Free Mode
          </Link>
        </nav>
      </header>

      <main className="bg-white shadow-md rounded-lg p-8">
        <h2 className="text-2xl font-semibold mb-4">Welcome Back 👋</h2>
        <p className="text-gray-600 mb-6">
          Upload your study materials, manage your subjects, and get AI-powered
          help with understanding concepts, tracking progress, and staying
          motivated.
        </p>

        <div className="grid md:grid-cols-3 gap-6">
          <div className="bg-blue-50 p-6 rounded-lg shadow hover:shadow-md">
            <h3 className="text-lg font-semibold mb-2">📚 Study Workspace</h3>
            <p className="text-sm text-gray-600 mb-3">
              Create or open subject-based workspaces for personalized
              assistance.
            </p>
            <Link
              to="/workspaces"
              className="text-blue-600 font-semibold hover:underline"
            >
              Open Workspace →
            </Link>
          </div>

          <div className="bg-green-50 p-6 rounded-lg shadow hover:shadow-md">
            <h3 className="text-lg font-semibold mb-2">🧠 Exam Mode</h3>
            <p className="text-sm text-gray-600 mb-3">
              Practice questions generated by AI based on your uploaded notes
              and PDFs.
            </p>
            <Link
              to="/exam-mode"
              className="text-green-600 font-semibold hover:underline"
            >
              Try Exam Mode →
            </Link>
          </div>

          <div className="bg-yellow-50 p-6 rounded-lg shadow hover:shadow-md">
            <h3 className="text-lg font-semibold mb-2">💬 Stress-Free Mode</h3>
            <p className="text-sm text-gray-600 mb-3">
              Talk to AI for motivation or stress relief — stay positive while
              studying.
            </p>
            <Link
              to="/stress-free"
              className="text-yellow-600 font-semibold hover:underline"
            >
              Launch →
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
